name = "Exponent"
author = "BlocoVermelho"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0009f65af810218d0aeac7465af10bedde05061297609de0700b9a9ab56987b"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
