name = "Exponent"
author = "roridev et. al"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0050cfadbd1d1a696b5bf7d25417c87dd0b8800f44be9e1f6403867fbd7345c3"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0"
