name = "exponent"
author = "alikindsys"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c50965453392cadf21ca6865ee9910e721007fcc997fee4e227b0bee4d2f38d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
