name = "Exponent"
author = "BlocoVermelho"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8c74266f1d11dbfbe1800491f8671de29c0b3dff2691e16810b13af6be9408b"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
