name = "Exponent"
author = "roridev et. al"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c4fbbeef10c8a75a348a7b772d7706e0b8c10a863ab22660b8521f2b5d04d44"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0"
