name = "Exponent"
author = "roridev et. al"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b59c9f04dff53de94b10c9c2034314484c3cd7356a31288b099217a07cb6ad2"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
