name = "Exponent"
author = "roridev et. al"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3366323e6f499da86e632ddf257a9a1e75eaa55a574b082c8fae9be2aabf74f4"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
