name = "Exponent"
author = "roridev et. al"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e76b6849f9ab36e100a054f89be908366d6d0b898049d18fa934e6138eb2ac7d"

[versions]
minecraft = "1.20.1"
quilt = "0.22.0"
