name = "Exponent"
author = "roridev et. al"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb51d13ff871852be2c4d89c76473e5fbedbff5d9851294a63534f2e2f37382a"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
