name = "Exponent"
author = "roridev et. al"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38e3a9e79a7a55ed83b9b8cf2d2350909f2e2764b402f77317cdc8a860d0beed"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
